### ISSUE TITLE
Client crash when just playing, not switching sound devices.

### ISSUE THREAD

**Issue by ProsperCraft** [ichttt/MoreSoundConfig#2]
https://gist.github.com/ProsperCraft/0df8151973e7309688fcbd1b4b6d85bc

**Comment by ichttt** [comment]
I don't think this is related to my mod, I don't do anything around PositionedSoundRecord... Hard to tell which line exactly is erroring, cause line numbers are misalligned. Most likely the sound is null. Did you change the sound device at all before the crash occured?

**Comment by ichttt** [comment]
So as I don't think that's my fault, as I really don't do anything in that code region, I'll close this
